name: CI/CD Pipeline for CareCompare_App

on:
  push:
    branches:
      - main
      - fix-ci-cd
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: carecompare_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Minion@1357$SA
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build the Application
        run: mvn clean package -DskipTests

      - name: Run Unit Tests
        run: mvn test

      - name: Build Docker Image
        run: |
          docker build -t carecompare_app:latest .
      
      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag and Push Docker Image
        run: |
          docker tag carecompare_app:latest ghcr.io/${{ github.repository_owner }}/carecompare_app:latest
          docker push ghcr.io/${{ github.repository_owner }}/carecompare_app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server (Optional)
        run: |
          echo "Deploying the application..."
          # Add SSH or deployment script if needed

